openapi: 3.0.0
info:
  version: 0.1.0
  title: CUSports Cart API
servers:
  - url: 'http://localhost:3000'
paths:
  /cart:
    post:
        summary: 'adds and item to the cart'
        operationId: AddCart
        parameters:
            -name: item will be in components
            description: item to be added
        responses:
            '200':
                description: 'succesfuly added an item to the cart'
    get:
      summary: 'retrive the current cart (returns array of items)'
      operationId: getCart
      
      parameters:
        - name: token
          in: query
          description: token for the user whose cart we are processing
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Cart successfully retrieved'
          content:
            application/json:
              schema:
                type: array
                items: 
                    $ref: '#/components/schemas/Item'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
            description: 'Error: cart not found'
     
components:
  schemas:
    Item:
      type: object
      required:
        - id
        - name
        - description
        - price
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        tag:
          type: string
    Responses:
      400Error:
        description: Invalid request
        content:
          application/json:
            schema:
              type: object
                message:
                  type: string
